#!/bin/bash
set -e

target_dir="$1"
pkg_out_dir="$2"
file_list="$3"

rm -rf "${pkg_out_dir}"
mkdir -p "${pkg_out_dir}"

if [ ! -s "${file_list}" ]; then
	exit 0
fi

awk -F, '{print $2}' "${file_list}" | rsync -a --files-from=- "${target_dir}/" "${pkg_out_dir}/"
